baseURL = "https://mnagaso.github.io/"
languageCode = "en-us"
title = "Web CV of Masaru NAGASO"
theme = "cactus"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "I am a post doctoral researcher living in Marseille/France🇫🇷. My scientific interest is Numerical modeling of a wave propagation🔊 and performance optimization of numerical code for HPC💻. I am also interested in the recent techniques of computer science including cluster detection, natural language processing, transformer, encoder-decoder etc... and cats😽. I can speak English(fluent), French(intermediate) and Japanese(native)."
  mainSection = "resume" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 0 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/mnagaso" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  showReadTime = false # default

  # custom css
  customCSS = ["css/custom.css"]

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/mnagaso"
  [[params.social]]
    name = "gitlab"
    link = "https://gitlab.com/mnagaso"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/nagaso-masaru-6b20705a"
  [[params.social]]
    name = "email"
    link = "nagaso@lme.cnrs-mrs.fr"  # no need for "mailto:" in the head
  [[params.social]]
    name = "email"
    link = "mnsaru22@gmail.com"  # no need for "mailto:" in the head
